#!/bin/bash

source=target/ROOT.war
destination/home/ec2-user/javaapp

$PWD/remote_access

$PWD/install_pacotes

$PWD/install_application

$PWD/install_appserver

$PWD/install_webserver

$PWD/stop_server

$PWD/start_server



